### ISSUE TITLE
Plan: MVP 0.5 tasks

### ISSUE THREAD

**Issue by BeckyPollard** [badgateway/tt-app#40]
### Let's get the app into a place where the basic user flow is successful!

The focus of "MVP 0.5" is all about getting the basic functions of the app's idea working. A user should be able to:
1. Log in or register.
2. Create & edit a client.
3. Create & edit a project.
4. Log hours to a timesheet & edit entry.

## Tasks List
- [ ] App has login screen.
- [x] Users can create and edit Clients.
- [ ] Users can create and edit Projects
  - [ ] https://github.com/badgateway/tt-app/issues/31
- [x] Users can create and edit People.
- [ ] Users can log and edit time for projects.

When the user flow of the app can be satisfied, 0.5 will be achieved!

References:
➤ [User flow description from the Notion document](https://www.notion.so/Time-tracker-e2c07e71b55442e4a67de8c95fa90a00#db6be7d760a440168d0477b043f67227).
