### ISSUE TITLE
App plan: MVP 1 tasks

### ISSUE THREAD

**Issue by BeckyPollard** [badgateway/tt-app#42]
### Hey the app's core functions work now, let's make it better to use!

The focus of "MVP 0.5" is all about how the user interacts with the app, and how the functionality is used throughout the screens. We'll improve the design, user experience, and functionality of the app. We also want to create a new screen for monthly client reports where all the timesheet info is displayed in one place as summary, and a landing page with info about the current user's data.

## Tasks List
**Client reports screen** ![new](https://user-images.githubusercontent.com/52248161/193344394-9d589dd7-efe5-4f9e-826f-066e4c1b239d.gif)
- [ ] https://github.com/badgateway/tt-app/issues/24
- [ ] https://github.com/badgateway/tt-app/issues/25
- [ ] https://github.com/badgateway/tt-app/issues/26

**Timesheets**
- [ ] https://github.com/badgateway/tt-app/issues/27
- [ ] https://github.com/badgateway/tt-app/issues/28

**App**
- [ ] Better UI for all screens.
- [ ] Build a landing page for root screen.

----

References:
➤ [User flow description from the Notion document](https://www.notion.so/Time-tracker-e2c07e71b55442e4a67de8c95fa90a00#db6be7d760a440168d0477b043f67227).
